version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker-files/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: docker-files/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
