name: Pull Request Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  greet_contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"body": "👋 Thanks for the pull request! Our team will review it soon."}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run Python linter (Pylance)
        run: |
          # Run pylint and capture both stdout and stderr
          pylint_output=$(pylint *.py 2>&1)
          echo "$pylint_output" > pylint_output.txt  # Save output to a file
          
          # Extract the score from the output
          score=$(echo "$pylint_output" | grep -oP 'Your code has been rated at \K[0-9]*\.[0-9]+')
          echo "Pylint Score: $score"
          
          # Check if the score is below 4.5
          if (( $(echo "$score < 4.5" | bc -l) )); then
            echo "Pylint score is below 4.5. Failing the workflow."
            cat pylint_output.txt  # Optionally show output when failing
            exit 1
          fi

      # Will need later if there are tests already
      # - name: Run tests
      #   run: |
      #     pytest
